### ISSUE TITLE
"justCTF/Forgotten name" wrong URL

### ISSUE THREAD

**Issue by roodypoole** [k01m3t/CTFs#1]
[](https://github.com/k01m3t/CTFs/blob/main/CTF-Writeups/2021/JustCTF/Forgotten%20name/README.md)

At the end you put a relative link to an external URL
`you can use <a href="crt.sh">crt.sh</a> to get the domain`

That should be
`you can use <a href="https://crt.sh/">crt.sh</a> to get the domain`

**Comment by k0imet** [comment]
ah  my bad ..was in a hurry, thanks for the input

**Comment by k0imet** [comment]
solved now
